cd: integrate cicd steps

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,4 +1,4 @@
-name: cd
+name: CI/CD
 
 on:
   pull_request:
@@ -6,7 +6,39 @@ on:
   workflow_dispatch:
 
 jobs:
-  deploy:
+  ci:
+    name: CI
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Start Docker Compose
+        run: |
+          docker-compose up -d
+        continue-on-error: true
+        timeout-minutes: 5
+
+      # - name: Wait for services to become healthy
+      #   run: |
+      #     retries=0
+      #     until docker-compose ps | grep -q "Up.*\(db\|redis\).*healthy"; do
+      #       retries=$((retries+1))
+      #       if [ $retries -gt 30 ]; then
+      #         echo "Services did not become healthy within timeout period."
+      #         exit 1
+      #       fi
+      #       sleep 10
+      #     done
+
+      - name: Run tests
+        run: docker-compose exec -T web ./run_test.sh
+
+      - name: Stop Docker Compose
+        run: docker-compose down
+
+  cd:
+    name: CD
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
