cd: fix cicd steps

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -40,31 +40,31 @@ jobs:
   cd:
     name: CD
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y awscli
+        env:
+          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
       - name: Deploy to EC2
         run: |
-          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-18-166-61-81.ap-east-1.compute.amazonaws.com 'bash -s' << EOF
-            cd ./dcard-golang-project
-            docker-compose down
-            git pull
-            docker-compose up -d
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-18-166-61-81.ap-east-1.compute.amazonaws.com '
 
-            sleep 10
+          cd ./dcard-golang-project
+          docker-compose down
+          git pull
+          docker-compose up -d
 
-            DOCKER_COMPOSE_STATUS=$?
+          sleep 10
 
-            if [ $DOCKER_COMPOSE_STATUS -eq 0 ]; then
-                echo "Docker Compose started successfully."
-            else
-                echo "Docker Compose failed to start."
-            fi
-            exit $DOCKER_COMPOSE_STATUS
-          EOF
+          DOCKER_COMPOSE_STATUS=$?
+
+          if [ $DOCKER_COMPOSE_STATUS -eq 0 ]; then
+              echo "Docker Compose started successfully."
+          else
+              echo "Docker Compose failed to start."
+          fi
+          exit $DOCKER_COMPOSE_STATUS
+          '
